### ISSUE TITLE
Populate single page with real copy

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/biffud.com#13]
Lets do this in https://docs.google.com/document/d/1eWF4Fcd9-RrY0YpP-C54zg8oJE5IPfFRDf_GXi3LZX4/edit?usp=sharing

The sections that need filling will be managed in that document for now; maybe some day we will move over to github.

**Comment by chriszs** [comment]
Depends on #16

**Comment by chriszs** [comment]
And #14

**Comment by chriszs** [comment]
About 50% done
