### ISSUE TITLE
Find BIFFUD quality pictures to replace the stock photos

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/biffud.com#14]
The template here shows how they fit in: https://lab.hyperaud.io/temp/biffud2/

Lets get some better pictures; feel free to upload them directly, or to post a link to them here.

We need to have the rights to use them.

**Comment by chriszs** [comment]
https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/es-090517-thinking-face-emoji-1504643347.jpg

**Comment by chriszs** [comment]
Do we want to use our logo? And where?
