### ISSUE TITLE
Write website copy

### ISSUE THREAD

**Issue by chriszs** [BadIdeaFactory/biffud.com#16]
Lets do this in https://docs.google.com/document/d/1eWF4Fcd9-RrY0YpP-C54zg8oJE5IPfFRDf_GXi3LZX4/edit?usp=sharing

**Comment by chriszs** [comment]
Should be part of the Initial Launch milestone. Can't add it. @slifty

**Comment by chriszs** [comment]
About 70% done

**Comment by slifty** [comment]
This is close enough to consider complete I think.  We can get more granular now if there's more to be written.
