### ISSUE TITLE
Add some more projects to our portfolio

### ISSUE THREAD

**Issue by chriszs** [BadIdeaFactory/biffud.com#35]

**Comment by slifty** [comment]
We need:

- [ ] ScriptChat (Lou)
- [ ] Overengineered Diplomacy (Dan)
- [ ] Truth Goggles (Dan)
- [ ] Talking Point Tracker (Dan)
- [ ] Aunty Beeb (Maboa)
- [ ] Montage (Maboa)

**Comment by slifty** [comment]
There is always more to add, but we got the main ones done.
