### ISSUE TITLE
Bio modals don't work on mobile

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/biffud.com#47]
(tested on iOS Chrome app)

The modals on chrome mobile don't seem to be overflowing as expected.  They don't have the ability to scroll, and text is cut off on the right hand side.

![file](https://user-images.githubusercontent.com/208884/49293477-4413b900-f47e-11e8-8196-e869c4c525e1.jpg)

**Comment by piotrf** [comment]
Fixed in https://github.com/BadIdeaFactory/biffud.com/commit/51020284fdd494c1d3dd5185043e430907f03278
