### ISSUE TITLE
"Fake"/"Real" FAQ titles are confusing, not in a good way

### ISSUE THREAD

**Issue by reefdog** [BadIdeaFactory/biffud.com#65]
I read "Fake FAQ" not as "questions that aren't actually frequently asked" but as "these answers are fake", yet the answers are real and accurate.

Consider something like "Kinda FAQ" (formerly "Fake") and "Actually FAQ" (formerly "Real")?

**Comment by slifty** [comment]
How do you know they aren't fake?

**Comment by reefdog** [comment]
You may try, but you cannot fully mask your aching sincerity!

**Comment by slifty** [comment]
What about "Official FAQ" and "Underground FAQ"

or maybe "Directors Cut FAQ"

**Comment by chriszs** [comment]
I like it because it's like how the kids today have rinstas and finstas, as the j-dog taught us. I shared reef's expectation, but isn't "not in a good way" just another way of saying it's a bad idea?

**Comment by slifty** [comment]
How about "Good FAQ" and "Bad FAQ"

**Comment by chriszs** [comment]
Frequently Asked Questions, "Frequently" "Asked" "Questions"

Although I feel like we did the sarcastic quotes somewhere else.

**Comment by slifty** [comment]
(we did... in the FAQ)

**Comment by chriszs** [comment]
Awkward. I'm going to blame this on somebody else.

**Comment by reefdog** [comment]
"not in a good way" was a terrible way to say it. I meant, "not in a way which enhances one's ultimate enjoyment upon understanding them".

I also think our lack of a good alternative means KEEP 'EM

**Comment by louh** [comment]
6 years later:

KEPT!!
