### ISSUE TITLE
Twitter cards don't work

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/biffud.com#66]
Twitter cards require absolute URLs, but gatsby image import in production uses relative urls.  I don't know exactly how to fix this but I'm sure there has to be a way.

**Comment by piotrf** [comment]
Where are Twitter cards? There’s a gatsby plugin for it: https://www.gatsbyjs.org/packages/gatsby-plugin-twitter/

**Comment by slifty** [comment]
It's just the og:image metadata

the point is og:image content={URL} <-- that URL needs to ultimately render an absolute URL for twitter to show the proper share image.

**Comment by piotrf** [comment]
`import { ogimage } from "assets/images";`

and 

`<meta property="og:image" content={ogimage} />`

should suffice.

**Comment by slifty** [comment]
I believe that's what we have (https://github.com/BadIdeaFactory/biffud.com/blob/master/lib/ui/partials/Helmet.js#L53) -- it renders as a relative path:

`<meta property="og:image" content="/static/portrait-faf5926a4a8fe902f106cfc758e6a124.png" data-react-helmet="true">`

It needs to be:

`<meta property="og:image" content="https://biffud.com/static/portrait-faf5926a4a8fe902f106cfc758e6a124.png" data-react-helmet="true">`

**Comment by piotrf** [comment]
Oh, okay, so then that image needs to land in `static`, gatsby will copy it automatically at build time, and it will be then accessible with an absolute path.

**Comment by piotrf** [comment]
I may have fixed that here: https://github.com/BadIdeaFactory/biffud.com/commit/7e138964b1a979ffe2e961c45b78b189f41d1159 We’ll know once this gets deployed.

**Comment by piotrf** [comment]
No, Twitter card images can be max 4096px in size either way. Ours was too big. This should now be fixed in https://github.com/BadIdeaFactory/biffud.com/commit/cddfd238140a7f4d5f4fb38350fb9ec0033ff36f
