### ISSUE TITLE
404 music doesn't always autoplay on Chrome

### ISSUE THREAD

**Issue by chriszs** [BadIdeaFactory/biffud.com#67]
Console error:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
```

**Comment by louh** [comment]
Related: [https://developers.google.com/web/updates/2017/09/autoplay-policy-changes](Chrome developer blog - Autoplay Policy Changes)

tl;dr: We are unlikely to override Chrome's strict restriction on autoplaying media.

Yes, many artists, game developers, etc. are mad. But adtech abused the API and so this is why we can't have nice things.

**Comment by chriszs** [comment]
Proposal: button that says "don't click this"

**Comment by slifty** [comment]
That's a good, solid proposal.

What I had in mind which I think mayyyy be a solid idea is a giant modal that fills the screen that says "Click Here To View our 404 Page" and if you click anywhere it closes and that triggers the play button.

**Comment by louh** [comment]
Investing any amount of time in making a project out of 404 pages, instead of, like, fixing broken links, is the kind of thing that would have blown my gasket at any of my previous companies, so strangely enough I approve of this

**Comment by chriszs** [comment]
Seems to work for me now. Good enough. Closing.
