### ISSUE TITLE
change default branch to 'main' or 'default'

### ISSUE THREAD

**Issue by sugaroverflow** [BadIdeaFactory/biffud.com#80]
let's change our default branch to `main` or `default`

possible solution: https://gist.github.com/PurpleBooth/6983e5c4def4f8721d4a697a3f4606a7#file-change-github-default-branch-sh

**Comment by louh** [comment]
Bumping for visibility. GitHub makes changing branch name to `main` super easy! There are only a couple of coordinating things to handle:

- [ ] Anyone who has this repo cloned locally and is expecting to contribute in the future should update their remote settings. GitHub will provide command line instructions for this.
- [ ] Third party services that are hooked into changes to this repo (e.g. Netlify) need to be repointed to the new branch name.

**Comment by slifty** [comment]
CI was broken anyway so seemed like a fine time to do this!

I've done it :D

CI is, of course, still broken.
