### ISSUE TITLE
Upgrade compatible Node version

### ISSUE THREAD

**Issue by chriszs** [BadIdeaFactory/biffud.com#94]
@slifty writes:
> I ended up trying out `act` and it revealed that the site doesn't build in Node 14.
>
> Updating the PR to specify 10 for our action (and I'm adding 10 to our package)

Node 10 was [end-of-lifed](https://twitter.com/nodejs/status/1388116425361874945) in April with a recommendation to upgrade to 14. Current LTS is 16 and current stable is 17.

**Comment by louh** [comment]
try this #97

**Comment by slifty** [comment]
I think this is closed!  Thanks @louh!
