### ISSUE TITLE
Custom domain is overwritten on deploy

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/biffud.com#95]
We just switched over to github actions which uses the `gh-pages` npm tool.  For some reason it's overwriting the custom domain.

The good news is [we're not alone](https://github.com/tschaub/gh-pages/issues/127), and it looks like the solution is to add a `CNAME` file somewhere.

What that file should contain and where it should go is anybody's guess (though it's probably explained in that issue)

**Comment by chriszs** [comment]
Like 90% sure I fixed it.

**Comment by slifty** [comment]
Amazing!  Thank you @chriszs -- it does indeed look fixed!

**Comment by chriszs** [comment]
In fd640b0d1ce0b59ab69f509a1af5c95950729b6f.
