### ISSUE TITLE
Blog post background flashing

### ISSUE THREAD

**Issue by louh** [BadIdeaFactory/biffud.com#99]
Here's the problem - https://github.com/BadIdeaFactory/biffud.com/blob/3dd3f26d4d18a1edbef77727f248d4eb4b466d16/lib/ui/templates/BlogPostTpl.js#L15

Fix would be to make a subcomponent for the reading time that manages timer state by itself, rather than at the page template level where it causes the entire page to re-render.

**Comment by maboa** [comment]
Suggest we disable in the meantime?
